### ISSUE TITLE
No such file or directory: './models/seated_nude.pth.tar'

### ISSUE THREAD

**Issue by yanmingqiang** [minhmanho/respecting_content_ist#1]
Hello, when I run the run.py file, the problem of No such file or directory:'./models/seated_nude.pth.tar' appears. Can you help me solve it?

**Comment by minhmanho** [comment]
Hi,

Thank you for reaching out.
Did you download models successfully?

`bash ./models/fetch_models.sh`

Wget seems unstable.
I just updated the file ./models/fetch_models.sh that I have changed wget to gdown.
Please install the gdown via command

`pip install gdown`

and pull this repo again, then run

`bash ./models/fetch_models.sh`

Best,

**Comment by yanmingqiang** [comment]
Thank you for your help, the previous problem has been solved. In addition, I would like to ask, if I want to retrain a new model, how can I do it?

**Comment by minhmanho** [comment]
I intend to not publish the training code.
You can refer to this PyTorch example to code one https://github.com/pytorch/examples/tree/master/fast_neural_style
then change the network in the file fast_neural_style/neural_style/transformer_net.py to my network https://github.com/minhmanho/respecting_content_ist/blob/master/networks.py
